// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	entity "e-wallet/entities"

	mock "github.com/stretchr/testify/mock"
)

// WalletService is an autogenerated mock type for the WalletService type
type WalletService struct {
	mock.Mock
}

// FindOneUser provides a mock function with given fields: userId
func (_m *WalletService) FindOneUser(userId int32) (*entity.UserCompact, error) {
	ret := _m.Called(userId)

	var r0 *entity.UserCompact
	if rf, ok := ret.Get(0).(func(int32) *entity.UserCompact); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserCompact)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int32) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TopUp provides a mock function with given fields: payload
func (_m *WalletService) TopUp(payload entity.AcceptedTxPayload) (*entity.UserCompact, *entity.TransactionRecord, string, error) {
	ret := _m.Called(payload)

	var r0 *entity.UserCompact
	if rf, ok := ret.Get(0).(func(entity.AcceptedTxPayload) *entity.UserCompact); ok {
		r0 = rf(payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserCompact)
		}
	}

	var r1 *entity.TransactionRecord
	if rf, ok := ret.Get(1).(func(entity.AcceptedTxPayload) *entity.TransactionRecord); ok {
		r1 = rf(payload)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entity.TransactionRecord)
		}
	}

	var r2 string
	if rf, ok := ret.Get(2).(func(entity.AcceptedTxPayload) string); ok {
		r2 = rf(payload)
	} else {
		r2 = ret.Get(2).(string)
	}

	var r3 error
	if rf, ok := ret.Get(3).(func(entity.AcceptedTxPayload) error); ok {
		r3 = rf(payload)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// Transfer provides a mock function with given fields: payload
func (_m *WalletService) Transfer(payload entity.AcceptedTxPayload) (*entity.UserCompact, *entity.TransactionRecord, error) {
	ret := _m.Called(payload)

	var r0 *entity.UserCompact
	if rf, ok := ret.Get(0).(func(entity.AcceptedTxPayload) *entity.UserCompact); ok {
		r0 = rf(payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserCompact)
		}
	}

	var r1 *entity.TransactionRecord
	if rf, ok := ret.Get(1).(func(entity.AcceptedTxPayload) *entity.TransactionRecord); ok {
		r1 = rf(payload)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entity.TransactionRecord)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(entity.AcceptedTxPayload) error); ok {
		r2 = rf(payload)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ViewTransactionsList provides a mock function with given fields: userId, searchQ, recipientQ, from, until, sortBy, sortOrder, limit, currentPage
func (_m *WalletService) ViewTransactionsList(userId int32, searchQ string, recipientQ string, from string, until string, sortBy string, sortOrder string, limit int32, currentPage int32) (*[]entity.TransactionRedacted, int32, error) {
	ret := _m.Called(userId, searchQ, recipientQ, from, until, sortBy, sortOrder, limit, currentPage)

	var r0 *[]entity.TransactionRedacted
	if rf, ok := ret.Get(0).(func(int32, string, string, string, string, string, string, int32, int32) *[]entity.TransactionRedacted); ok {
		r0 = rf(userId, searchQ, recipientQ, from, until, sortBy, sortOrder, limit, currentPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]entity.TransactionRedacted)
		}
	}

	var r1 int32
	if rf, ok := ret.Get(1).(func(int32, string, string, string, string, string, string, int32, int32) int32); ok {
		r1 = rf(userId, searchQ, recipientQ, from, until, sortBy, sortOrder, limit, currentPage)
	} else {
		r1 = ret.Get(1).(int32)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(int32, string, string, string, string, string, string, int32, int32) error); ok {
		r2 = rf(userId, searchQ, recipientQ, from, until, sortBy, sortOrder, limit, currentPage)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
